# ---------- Configuration ---------------

mail:
  username: abd@xyz.com
  password: foobar
  imap:
    server: imap.gmail.com
    port: 993
  smtp:
    server: smtp.gmail.com
    port: 465
  archive-folder: archive-folder-name
  archive: true

joplin:
  default-title-prefix: New Note
  default-notebook: Inbox
  auto-create-notebook: true
  auto-sync: true
  mailbox: Joplin
  api-port: 41184
  api-key: <api-key>