# ---------- Configuration ---------------

timezone: America/Denver

mail:
  smtp:
    server: <smtp server>
    port: 465
    username: foo@bar.com
    password: abc123
  accounts:
    - name: xyz456
      username: foo@bar.com
      password: abc123
      imap:
        server: <imap server>
        port: 993
      mail-forward:
        <mailbox 1>: <email to forward to>
        <mailbox 2>: <email to forward to>
  archive: true

joplin:
  default-title-prefix: New Note
  default-notebook: Inbox
  auto-create-notebook: true
  auto-create-tag: false
  mailbox: Joplin
  directory: <path to folder>
  api-port: 41184
  api-key: <api key>>
  auto-sync: false
  delete-processed: false
  processed-tag: <tag name>
  ocr-tag: <tag name>

file:
  archive: <path>

todoist:
  api-key: <api key>
  joplin-tag: <tag name>
  joplin-notebook: <notebook name>
  service:
    joplin:
      tag-mapping: [<from tag name>, <to tag name>]
      processed-tag: <tag name>

kindle:
  joplin-tag: <tag name>
  joplin-notebook: <notebook name>
  email: <Kindle device email>

trello:
  email: <Trello board email>
  joplin-tag: <tag name>
  joplin-notebook: <notebook name>

